# Start with a VNC service with a new dedicated Docker image
image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: install dev env
    init: |
        cargo install create-tauri-app --locked
        cargo install tauri-cli --version '^2.0.0' --locked
        curl -fsSL https://deno.land/install.sh | sh
        export PATH=$PATH:/home/gitpod/.deno/bin/
        deno i
    command: |
        deno task tauri dev


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
    extensions:
        - Vue.volar
        - tauri-apps.tauri-vscode
        - rust-lang.rust-analyzer
        - saoudrizwan.claude-dev
